# Generated by Django 3.0.2 on 2020-01-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.BigIntegerField(verbose_name=10)),
                ('customer_email', models.EmailField(max_length=250)),
                ('own_business', models.CharField(max_length=10)),
                ('customer_password', models.CharField(max_length=150)),
                ('is_registration_active', models.CharField(max_length=5)),
                ('customer_created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
